#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Apr 16 23:39:58 EDT 2024
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto b62df80cab434fdd980a082523a3abd3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot uproc_top_level_wrapper_tb_behav xil_defaultlib.uproc_top_level_wrapper_tb -log elaborate.log"
xelab -wto b62df80cab434fdd980a082523a3abd3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot uproc_top_level_wrapper_tb_behav xil_defaultlib.uproc_top_level_wrapper_tb -log elaborate.log

